### ISSUE TITLE
couldn't get it working on windows 10 64bit

### ISSUE THREAD

**Issue by srg-n** [CrazyRedMachine/Prodikeys64#2]
hello there,
i did install the WinUSB driver and teVirtualMIDI with loopMidi but still cannot get prodikeys64.exe to see it. any clue what might be the issue? i'm really looking forward to troubleshoot this.

![image](https://user-images.githubusercontent.com/8938967/134567152-54d7324e-3b90-4d1a-a413-984f5eab20fe.png)
![image](https://user-images.githubusercontent.com/8938967/134567329-fcbf7c92-211d-4c6c-a0ea-0ea2c741d3fe.png)

also tried installing microsoft's updated winusb driver with device manager
![image](https://user-images.githubusercontent.com/8938967/134567260-590918f3-8672-44ec-b806-0ffa31dd8edb.png)

tried all cliche options as well, such as remove device on device manager, install on zadig with/without admin prompts, updating my windows to the latest version, a different windows 10 pc, etc.

i get this error with both versions
![image](https://user-images.githubusercontent.com/8938967/134567399-cdd961a3-7ca1-427b-a112-ba38703c7563.png)
clicking ignore makes the program launch but still, midi keys don't work at all.

i don't think that there's a problem with my keyboard either since it works on kubuntu 20.04 without installing anything additional.

**Comment by CrazyRedMachine** [comment]
Hi,

Sorry about that, the issue is with win10 usbhid driver now opening mice and keyboard devices in exclusive mode (which means it's not possible for another application to read/write hid reports communicating with this device). This was a security measure against keyloggers and similar apps. 

This means it is now impossible for libusb to open part of a keyboard device (midi is on a separate interface) while letting windows manage it. I had a lead for a workaround but haven't got around to implement it yet... I've got to update the readme (or the code, or both lol).

**Comment by srg-n** [comment]
thank you,
can you talk about the details a little? i'm also okay with removing pc keyboard interface and only getting midi keyboard section working.

**Comment by CrazyRedMachine** [comment]
in this case you should be able to use this soft as long as you install the winusb driver for both interface 0 and 1. (you'll lose the hid keyboard but my prodikeys soft should be able to open the device)

**Comment by srg-n** [comment]
thank you so much! that did the trick.

**Comment by simondavidbond** [comment]
Please can you help me?

I have a Prodikeys keyboard & run Windows 11, I have followed your instructions but it does not work. I have:-

1. Downloaded Run & setup Zadig as you suggested,
2. Downloaded & installed loopMidi,
3. Run Prodikeys64.exe,
4. Restarted

But 

![Image](https://github.com/user-attachments/assets/76a07905-ba06-4fbe-ac79-f9e9dbd43135)

I still can't get it to work.

Any help would be appreciated!

Thanks,

Si.

**Comment by CrazyRedMachine** [comment]
hi,
you're supposed to run prodikeys64.exe so that it can create the virtual midi device, loopmidi is just a mean to get teVirtualMidi driver to install.

when everything is installed, you can run prodikeys64 and enable piano mode in there, then your midi-compatible app (synthesia, etc..) should be able to see the prodikeys device

**Comment by simondavidbond** [comment]
Thanks,

I know it's a big ask, but please can you send me a step by step list of what I need to do to get my Prodikeys working in Windows 11? Like a guide for dummies!!

I'm basically an electronics hardware engineer, so I don't fully understand how to get the Prodikeys working.

Thanks,

Si.


Si Bond.

=============================
= Simon.D.Bond MEng(Hons), BSc(Hons) =
=============================
________________________________

**Comment by CrazyRedMachine** [comment]
I just went through setting it up on my win11 pc, so here's the full step by step guide 
(looking at your previous screenshots, I think you mostly lack an app to use your piano with... 
looks like you can jump straight to confirming teVirtualMIDI device is there in Device Manager, then install synthesia, run prodikeys and enjoy)

## PREREQUISITES 

### A Prodikeys usb keyboard (duh)

plug prodikeys keyboard to your pc, the keyboard should work, but not the piano
 
### Winusb driver (to make prodikeys64 able to communicate with the prodikeys piano)

- download zadig ( https://github.com/pbatard/libwdi/releases/download/v1.5.1/zadig-2.9.exe )
- use zadig to replace usbhid driver with winusb driver on "Interface 1" (and on Interface1 ONLY, don't touch interface 0 or you'll lose the pc keyboard). 
- BE PATIENT, this step takes several minutes to complete... if it asks for a reboot, select "reboot later", wait for the "Installation complete" message before rebooting
- Once succesfully replaced, it should look like this:![Image](https://github.com/user-attachments/assets/29fa64bf-8c51-4876-9d8b-bed018f8940b)

### teVirtualMIDI (to make your prodikeys+prodikeys64.exe appear as a midi-compliant device on your system)

- Download and install either LoopMIDI or teVirtualMidiSDK ( https://www.tobias-erichsen.de/wp-content/uploads/2020/01/teVirtualMIDISDKSetup_1_3_0_43.zip ). 
- Once installed, in Win+X -> Device Manager you should be able to see the "teVirtualMIDI device"

![Image](https://github.com/user-attachments/assets/47b77d1c-d4a7-4336-b705-4857202bfdc4)

### A midi compatible application to use your midi keyboard with (I'm using Synthesia for example)

- Download and install Synthesia ( https://synthesiagame.com/get?platform=win )

## USING PRODIKEYS64 

- Download https://github.com/CrazyRedMachine/Prodikeys64/releases/download/v1.1/Prodikeys64_v1.1.zip
- Extract and run prodikeys64.exe, this should give you a little piano icon system tray : 
 
![Image](https://github.com/user-attachments/assets/50873095-1ed4-456a-8aa0-0188cb868f20)

- If you right click on it you can select "Activate Midi" (or you can also press the top left piano key on your prodikeys)
![Image](https://github.com/user-attachments/assets/14ec07a1-4d53-408e-8c89-59340bbd2c80)

## USING SYNTHESIA WITH PRODIKEYS64 

Now that the midi is activated, go into Synthesia settings, you should see "Prodikeys MIDI Interface"

![Image](https://github.com/user-attachments/assets/12e43fb8-e8b7-455c-988b-19394ab5cb72)

Click on it then click "Use input from this device", and finally press the first and last key of the piano to correctly set the 37-key range (you should see the keys you press turning green on the app, and hear them)

![Image](https://github.com/user-attachments/assets/04fcde9d-be45-4371-8fa4-4646663f9d89)

Congrats you can use your prodikeys to play with synthesia now :)

**Comment by simondavidbond** [comment]
Thanks,

Just got it!

I'm kinda old school when it comes to this kind of thing, like build chains & the various software components. I'm fine with C.

I shall try this out tomorrow.

It might be a good idea for you to share the instructions, as the more I searched there are plenty of people who want to get a Prodikeys working. It is such a good idea, but I don't know why Creative stopped supporting it.

Then again Creative doesn't seem to have groundbreaking sound cards for computer music any more (AWE32/64). They seem focused on games & surround sound.

I had to get an external audio interface that could cope with multiple VSTi (Lexicon Lambda).

My aim is to create computer music. I have GarageBand & Sonar plus some very good virtual instruments. I use my Akai EWI as MIDI input, but I'd like to also have a MIDI keyboard too - that's why I kept my Prodikeys, I can just remove the keyboard cover rather than setting up a larger keyboard.

Thanks,

Si.

-----------------------
Simon David Bond MEng, BSc(Hons).
-----------------------


On 28 Apr 2025, at 8:34 pm, CrazyRedMachine ***@***.***> wrote:

﻿
[https://avatars.githubusercontent.com/u/36906596?s=20&v=4]CrazyRedMachine left a comment (CrazyRedMachine/Prodikeys64#2)<https://github.com/CrazyRedMachine/Prodikeys64/issues/2#issuecomment-2836305911>

I just went through setting it up on my win11 pc, so here's the full step by step guide
(looking at your previous screenshots, I think you mostly lack an app to use your piano with...
looks like you can jump straight to confirming teVirtualMIDI device is there in Device Manager, then install synthesia, run prodikeys and enjoy)

PREREQUISITES
A Prodikeys usb keyboard (duh)

plug prodikeys keyboard to your pc, the keyboard should work, but not the piano

Winusb driver (to make prodikeys64 able to communicate with the prodikeys piano)

  *   download zadig ( https://github.com/pbatard/libwdi/releases/download/v1.5.1/zadig-2.9.exe )
  *   use zadig to replace usbhid driver with winusb driver on "Interface 1" (and on Interface1 ONLY, don't touch interface 0 or you'll lose the pc keyboard).
  *   BE PATIENT, this step takes several minutes to complete... if it asks for a reboot, select "reboot later", wait for the "Installation complete" message before rebooting
  *   Once succesfully replaced, it should look like this:zadig_ok.png (view on web)<https://github.com/user-attachments/assets/29fa64bf-8c51-4876-9d8b-bed018f8940b>

teVirtualMIDI (to make your prodikeys+prodikeys64.exe appear as a midi-compliant device on your system)

  *   Download and install either LoopMIDI or teVirtualMidiSDK ( https://www.tobias-erichsen.de/wp-content/uploads/2020/01/teVirtualMIDISDKSetup_1_3_0_43.zip ).
  *   Once installed, in Win+X -> Device Manager you should be able to see the "teVirtualMIDI device"

image.png (view on web)<https://github.com/user-attachments/assets/47b77d1c-d4a7-4336-b705-4857202bfdc4>

A midi compatible application to use your midi keyboard with (I'm using Synthesia for example)

  *   Download and install Synthesia ( https://synthesiagame.com/get?platform=win )

USING PRODIKEYS64

  *   Download https://github.com/CrazyRedMachine/Prodikeys64/releases/download/v1.1/Prodikeys64_v1.1.zip
  *   Extract and run prodikeys64.exe, this should give you a little piano icon system tray :

image.png (view on web)<https://github.com/user-attachments/assets/50873095-1ed4-456a-8aa0-0188cb868f20>

  *   If you right click on it you can select "Activate Midi" (or you can also press the top left piano key on your prodikeys)
image.png (view on web)<https://github.com/user-attachments/assets/14ec07a1-4d53-408e-8c89-59340bbd2c80>

USING SYNTHESIA WITH PRODIKEYS64

Now that the midi is activated, go into Synthesia settings, you should see "Prodikeys MIDI Interface"

image.png (view on web)<https://github.com/user-attachments/assets/12e43fb8-e8b7-455c-988b-19394ab5cb72>

Click on it then click "Use input from this device", and finally press the first and last key of the piano to correctly set the 37-key range (you should see the keys you press turning green on the app, and hear them)

image.png (view on web)<https://github.com/user-attachments/assets/04fcde9d-be45-4371-8fa4-4646663f9d89>

Congrats you can use your prodikeys to play with synthesia now :)
